version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ../../FE/dist/g87:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # docker compose -p fe-nginx up -d