version: "3.8"
services:
  backend:
    build:
      context: ../BE
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb+srv://kelvinkel6886:mitthuy123456@g87.fbbhkmu.mongodb.net/g87
      - JWT_ACCESS_KEY=TRIG87
      - JWT_REFRESH_KEY=TRIG87
      - TELEGRAM_TOKEN=6115049677:AAG3TrLTgg8V0pGk-LTng6XYUDjwLQVc15Y
  frontend:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - ../FE/dist/t89:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

      # docker compose -p fe-nginx up -d
      #docker compose -p g87-all up -d